version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: "booking"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - booking-db:/var/lib/mysql
    networks:
      booking-network:

  booking-service:
    container_name: booking-service
    image: muhammedshaheer/booking-service
    build:
      context: .
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booking?serverTimezone=UTC"
      - "SPRING_DATASOURCE_USERNAME=user"
      - "SPRING_DATASOURCE_PASSWORD=password"
    ports:
      - 9701:9701
    networks:
      booking-network:
    depends_on:
      - db
volumes:
  booking-db:
networks:
  booking-network: